# Define shared volumes for caching
volumes:
  npm-cache:
    name: "npm-cache"
  nx-cache:
    name: "nx-cache"

services:
  shell:
    build:
      context: .
      dockerfile: apps/shell/Dockerfile
      args:
        APP_NAME: shell
        BUILDKIT_INLINE_CACHE: 1
        NODE_ENV: production
      cache_from:
        - shell:latest
    image: shell:latest
    ports:
      - "4200:80"
    volumes:
      - npm-cache:/root/.npm
      - nx-cache:/app/.nx/cache
    depends_on:
      - login
      - products
      - cart
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  login:
    build:
      context: .
      dockerfile: apps/login/Dockerfile
      args:
        APP_NAME: login
        BUILDKIT_INLINE_CACHE: 1
        NODE_ENV: production
      cache_from:
        - login:latest
    image: login:latest
    ports:
      - "4201:80"
    volumes:
      - npm-cache:/root/.npm
      - nx-cache:/app/.nx/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  products:
    build:
      context: .
      dockerfile: apps/products/Dockerfile
      args:
        APP_NAME: products
        BUILDKIT_INLINE_CACHE: 1
        NODE_ENV: production
      cache_from:
        - products:latest
    image: products:latest
    ports:
      - "4202:80"
    volumes:
      - npm-cache:/root/.npm
      - nx-cache:/app/.nx/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  cart:
    build:
      context: .
      dockerfile: apps/cart/Dockerfile
      args:
        APP_NAME: cart
        BUILDKIT_INLINE_CACHE: 1
        NODE_ENV: production
      cache_from:
        - cart:latest
    image: cart:latest
    ports:
      - "4203:80"
    volumes:
      - npm-cache:/root/.npm
      - nx-cache:/app/.nx/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
